engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: false
  bundler-audit:
    enabled: true
ratings:
  paths:
    - "app/**"
    - "bin/**"
    - "config/**"
    - "db/**"
    - "frontend/**"
    - "lib/**"
    - "test/**"
exclude_paths:
- Documents/**/*
- bourbon/**/*
- neat/**/*
- node_modules/**/*
- frontend/bower_components/**/*
- frontend/node_modules/**/*
- frontend/dist/**/*
- frontend/vendor/**/*
- public/**/*
- vendor/**/*
