engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
    checks:
      Similar code:
        enabled: false
ratings:
  paths:
    - "app/**"
    - "bin/**"
    - "config/**"
    - "db/**"
    - "frontend/**"
    - "lib/**"
    - "test/**"
exclude_paths:
- app/assets/images/**/*
- Documents/**/*
- db/**/*
- bourbon/**/*
- neat/**/*
- node_modules/**/*
- frontend/bower_components/**/*
- frontend/node_modules/**/*
- frontend/dist/**/*
- frontend/vendor/**/*
- public/**/*
- vendor/**/*
- "db/schema.rb"
- "README.md"
