languages:
  Ruby: true
  JavaScript: true
  PHP: true
  Python: true
 exclude_paths:
 - "vendor/*"
 - "frontend/vendor/*"
 - "frontend/bower_components/*"
 - "frontend/node_modules/*"
 - "public/assets/*"
