sudo: required
language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
- 2.0.0
before_script:
- bundle exec rake db:migrate
- bundle exec rake db:seed
- cd frontend
- sudo npm install
- sudo bower install
- npm install --save-dev ember-cli-rails-addon@0.1.11
- ember install ember-cli-simple-auth
- ember install ember-cli-simple-auth-devise
- cd ..
env:
- SECRET_KEY_BASE= "7a0800eed4fc8c5441fda5e8c803994b9cf8ad8fdb55ef75b25bd486390cf7f3e4b32a626a3907c09ea26c0dc877ccb0d40fa61f6270f33dbc3295347e6bd7e2"

