sudo: required
language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
- 2.0.0
before_script:
- bundle exec rake db:migrate
- bundle exec rake db:seed
- sudo apt-get install nodejs
- node --help
- npm --help
- npm install -g bower
- cd frontend
- npm install -g ember-cli
- sudo npm install
- sudo bower install
- npm install --save-dev ember-cli-rails-addon@0.1.11
- ember install ember-cli-simple-auth
- ember install ember-cli-simple-auth-devise
- cd ..
