language: node_js
sudo: true
cache:
  bundler: true
  directories:
    - frontend/node_modules
    - frontend/bower_components
node_js:
- "4"
before_install:
- openssl aes-256-cbc -K $encrypted_f7320bcbcc32_key -iv $encrypted_f7320bcbcc32_iv
  -in secrets.yml.enc -out config/secrets.yml -d
before_script:
- sudo apt-get install -y libpq-dev nginx ruby2.3 rails bundler
- cd frontend
- npm install
- bower install
script:
- cd ..
- bundle exec rake db:setup
- bundle exec rake test
- cd frontend
- ember test
after_script:
- CODECLIMATE_REPO_TOKEN=c3055c2ba9d4366d62a766320aad9097184a33532676588a5fd68536f85dc048 codeclimate-test-reporter < lcov.dat
