sudo: required
language: ruby
cache: bundler
branches:
  only:
  - master
rvm:
- 2.0.0
before_script:
- sudo apt-get install nodejs npm
- sudo apt-get update
- npm install -g bower
- cd frontend
- npm install -g ember-cli
- npm install
- bower install
- npm install --save-dev ember-cli-rails-addon
- ember install ember-cli-simple-auth
- ember install ember-cli-simple-auth-devise
- cd ..
- bundle exec rake db:migrate
- bundle exec rake db:seed
before_install:
- openssl aes-256-cbc -K $encrypted_f7320bcbcc32_key -iv $encrypted_f7320bcbcc32_iv
  -in secrets.yml.enc -out config/secrets.yml -d
addons:
  code_climate:
    repo_token: 9e561427bd3657e5d75929feb95d495b08e4b0fb665e4000bb58a1c42db1e382
