sudo: required
language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
- 2.0.0
before_script:
- sudo apt-get install nodejs npm
- sudo apt-get update
- npm install -g bower
- cd frontend
- npm install -g ember-cli
- npm install
- bower install
- npm install --save-dev ember-cli-rails-addon
- ember install ember-cli-simple-auth
- ember install ember-cli-simple-auth-devise
- cd ..
script:
- bundle exec rake db:migrate
- bundle exec rake db:seed
env:
  RAILS_ENV=test
  SECRET_KEY_BASE="$(bundle exec rake secret)"
