language: ruby
sudo: true
cache:
  bundler: true
  directories:
    - frontend/node_modules
    - frontend/bower_components
rvm:
- 2.3.0
before_install:
- openssl aes-256-cbc -K $encrypted_f7320bcbcc32_key -iv $encrypted_f7320bcbcc32_iv
  -in secrets.yml.enc -out config/secrets.yml -d
before_script:
- sudo apt-get purge nodejs npm
- sudo apt-get install npm
- sudo npm cache clean -f
- npm config set registry http://registry.npmjs.org/
- sudo npm install -g n
- sudo n stable
- sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
- cd frontend
- npm install
- bower install
script:
- cd ..
- bundle exec rake db:setup
- bundle exec rake test
- cd frontend
- ember test
after_script:
- CODECLIMATE_REPO_TOKEN=c3055c2ba9d4366d62a766320aad9097184a33532676588a5fd68536f85dc048 codeclimate-test-reporter < lcov.dat
